### ISSUE TITLE
Infinite Loop When Posting Preview to S3 Bucket with Python Tool

### ISSUE THREAD

**Issue by vfr292** [filepreviews/filepreviews-python#1]
Hi,

I look forward to using file previews, but I'm currently having some trouble posting the preview to my S3 bucket. 

I'm getting the debug messages below with the last line repeating hundreds of times.  While it could be a permissions issue on the S3 bucket, I've tried giving permission to everyone to list and upload objects.

```
DEBUG:filepreviews:Generating preview for http://www.rawsamples.ch/raws/canon/d30/RAW_CANON_D30_SRGB.CRW
DEBUG:filepreviews:Polling https://s3.amazonaws.com/post-great-pics-test-file-uploads/1d3aebcbd37ceb5a8f74bb2c10caa3b9a3d39001814baedbd50ab4de3bb1badf/metadata.json
DEBUG:filepreviews:Polling https://s3.amazonaws.com/post-great-pics-test-file-uploads/1d3aebcbd37ceb5a8f74bb2c10caa3b9a3d39001814baedbd50ab4de3bb1badf/metadata.json
....
```

Thank you for looking into this.  Please let me know if I can be of assistance.

~Victor

**Comment by jpadilla** [comment]
@vfr292 it seems they were correctly processed but the generic endpoint we're using for https and S3 is giving out an error, if I'm not mistake you're bucket is not in the US Standard(us-east-1) region, right?

We're wrongfully assuming that every bucket will be in the US Standard region. I've created a feature request for this since it's a very valid one.

**Comment by vfr292** [comment]
Thank you for the prompt response!

You are correct, my bucket is in Northern California.  Let me know when the bucket option is added, and I'll give it another try.

Thanks :)

~Victor

**Comment by vfr292** [comment]
Hi,

I wa curious if the team had had a chance to look at this.  I'd be happy to any changes a test.

~Victor

**Comment by jpadilla** [comment]
@vfr292 just deployed this new feature, and would love your feedback on it if you're still interested. You should be able to correctly set your S3 Region for your storage.

http://filepreviews.io/docs/storages.html

**Comment by vfr292** [comment]
Hi, Thank you for looking into this, but it is still not working.

I've added the region and when I click "try" on the website it is able to make a file "filepreviews.txt" in the S3 bucket.

It looks like the preview creation is successful (there is a screenshot in a subfolder in the S3 bucket)

However, my test script still gives me the same error:

<code>
DEBUG:filepreviews:Initializing FilePreviews
DEBUG:filepreviews:Generating preview for http://www.getblimp.com/images/screenshot1.png
DEBUG:filepreviews:Polling https://s3-us-west-1.amazonaws.com/post-great-pics-test-file-uploads/61534d67985538226702f6125434eaa29a24f6f55f804f7b662d958d0773c463/metadata.json
DEBUG:filepreviews:Polling https://s3-us-west-1.amazonaws.com/post-great-pics-test-file-uploads/61534d67985538226702f6125434eaa29a24f6f55f804f7b662d958d0773c463/metadata.json
...
</code>

It keeps polling until it errors out in an infinite loop.
My code is just:

<code>
api = FilePreviews(api_key = ''myke"', debug = True)
api_sample_result = api.generate('http://www.getblimp.com/images/screenshot1.png')
</code>

**Comment by jpadilla** [comment]
@vfr292 I think I might have found something wrong in all of this. I bet we're expecting that metadata.json to always be public. If you can in fact see the preview and metadata file but the polling is failing that has to be the case. Still need to replicate it though and figure out what the best solution might be.

Also, we're planning on refactoring a bit how these libraries work, they currently only support polling which is not always the desired behavior, e.g. fire and forget, get notified via webhooks.

**Comment by vfr292** [comment]
I granted everyone all of the S3 bucket permissions as captured in the screenshot below and still am getting the infinite polling loop error.  I don't think the polling error is caused by a lack of S3 permission.

![image](https://cloud.githubusercontent.com/assets/91652/7383347/68d9cd30-edd2-11e4-95c5-7f41f2f5919d.png)
